name: Wren Culp
favicon: null
layout_spectrum: 0.5887383376248181
typography_spectrum: 0.62649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d5a9a'
    - '#110607'
    - '#cccccc'
    - '#e48e3c'
    - '#663f40'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
