name: Wren Culp
favicon: null
layout_spectrum: 0.5887383376248181
typography_spectrum: 0.01212901552207768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5503048384562135
  lightness: 0.5067967104259878
  saturation: 0.7300425542052835
  rhythmicContrast: 0.18971110577695072
purpose: []
