typography_spectrum: 0.83017
color:
  brandColors:
    - '#000000'
    - '#003fab'
    - '#c7d4f9'
    - '#be969b'
    - '#008af9'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23205
analytics:
  google: null
  facebook: null
  twitter: null
name: Wren Culp
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: WREN Culp
description: I create stories and obsess over the Broncos
purpose: []
