name: Wren Culp
favicon: null
layout_spectrum: 0.23205
typography_spectrum: 0.83017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#003fab'
    - '#c7d4f9'
    - '#be969b'
    - '#008af9'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
